/**
 * ============================================================================
 * SECTION 34 – Validation Middleware (Handling express-validator Results)
 * ============================================================================
 * This middleware inspects the `validationResult(req)` object generated by
 * the express-validator check chains.
 *
 * If any validation errors exist:
 * - It short-circuits the request pipeline
 * - Returns a structured HTTP 400 Bad Request response containing the specific
 *   field names and error messages
 * If valid:
 * - Calls `next()` to pass control to the controller handler.
 * ============================================================================
 */

import { validationResult } from 'express-validator';

export function validate(req, res, next) {
  // Section 34 – Extract validation errors from the request
  const errors = validationResult(req);

  if (!errors.isEmpty()) {
    // Section 34 – Format error messages for API consumers
    const formattedErrors = errors.array().map(err => ({
      field: err.path || err.param,
      message: err.msg,
      value: err.value
    }));

    return res.status(400).json({
      success: false,
      message: 'Validation failed. Please check the submitted fields.',
      errors: formattedErrors
    });
  }

  // No validation errors, proceed to next middleware or controller
  next();
}

export default validate;
